### ISSUE TITLE
/tmp files are not being removed

### ISSUE THREAD

**Issue by reikred** [koknat/dif#2]
The title says it all: /tmp files are not being removed. Directories and files /tmp/d_XYZW/{1,2}__* are not being removed upon exit from tkdiff or meld or whatever gui is used.

Love the dif tool !! Really great and very practical tool !! But I  think /tmp should be cleaned up (unless invoked in some sort of debug mode, perhaps)

**Comment by koknat** [comment]
Thanks for the feedback, and I'm happy that you're finding the tool to be useful.

dif currently opens the GUI and exits immediately to the command line.
This means that there is no opportunity for temp file cleanup after the GUI is closed.

Possible enhancement:
dif would NOT immediately return to the command line (user would need to use '&' if that is desired).
Once the GUI is closed, dif would remove the tmp files and return to the command line.
This behavior could be disabled with a new option -keeptmp

**Comment by koknat** [comment]
I've enhanced the code to automatically clean up the /tmp files
Option -keeptmp disables the cleanup
