### ISSUE TITLE
compare directories - path is incorrectly concatenated 

### ISSUE THREAD

**Issue by lesioc** [koknat/dif#3]
Hi 
I really like the idea of the dif preprocessor, but unfortunately for me it keeps failing with incorrect file names :(
Looks like main path is doubled in the final filename

![image](https://user-images.githubusercontent.com/12273162/113476666-26efba80-947d-11eb-84f8-a9ac1132d3ac.png)

Regards
Leszek

**Comment by koknat** [comment]
Hi Leszek,

Does this happen with the latest version of the code?
The version is shown close close to the end of the script
"v44 Tue Mar 23 11:26:39 PDT 2021"

**Comment by lesioc** [comment]
Yes, I have used v44, Mar 23

**Comment by koknat** [comment]
I've reproduced the behavior.  It was triggered by the trailing '/'
The code has been updated.  Let me know if it's working now on your test case.
Thanks!
