### ISSUE TITLE
Filter out comments starting with ';'

### ISSUE THREAD

**Issue by gerrit-l** [koknat/dif#4]
Hi, I discovered your tool on StackExchange and really love it!
Got a problem with comparing asm files that have comments starting with ';'
I tried '-white -case -search ';' -replace '//' -comments' but it didn't filter out the comments as expected but showed all of them with '//'. meld does ignore my settings, too.
What can I do? Thanks!

**Comment by koknat** [comment]
I'm glad you're finding it useful!
Try this:
-search '\s*(;.*)?$' -replace ''
